title: Osita Gerald Abia
logo: /headshot.webp
description: A data analyst with 3 years experience using excel for report automation,sql for data manipulation and power Bi for Visualisation
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
