Osita Gerald Abia
logo: headshot
Description : A data analyst with 3 years experience using excel for report automation,sql for data manipulation and power Bi for insights 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
