title: Osita Gerald Abia
logo: WIN_20260903_20_37_18_Pro.jpg
description: A data analyst with 2 years experience using excel for report automation,sql for data manipulation and power Bi for Visualisation
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
